### ISSUE TITLE
Error: TypeError: _.foldl is not a function

### ISSUE THREAD

**Issue by maoo** [HadoukenIO/core#252]
Hi there,

I'm following the build instructions on the README, but I get the error mentioned on the title; below the steps to reproduce, output and environment specs; full logs are available on https://gist.github.com/maoo/20fc62e6af91d58d94d0ea4dff887feb

Thanks!

**Steps to reproduce**
```
git clone https://github.com/HadoukenIO/core.git
cd core
npm install
```

**Error**
```
Error: TypeError: _.foldl is not a function
Warning: Task "ts:default" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! openfin@0.0.1 postinstall: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the openfin@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m/.npm/_logs/2017-11-22T14_12_32_564Z-debug.log
------------------------------------------------------------
```

**Environment**
- macOS High Sierra, 10.13.1
- npm -v, no5.4.2
- node -v, v8.3.0

**Comment by HarsimranSingh** [comment]
Hi @maoo,

This is a known issue that may be related to our `npm-shrinkwrap.json`. If you use node `v6.9.0` as described in the `README.md`, it should build correctly. Let me know if it is still broken for you. We're working on resolving this issue with more recent versions of node.

-Sim

**Comment by maoo** [comment]
TY @HarsimranSingh , I'll try with `v6.9.0` and get back to you

**Comment by maoo** [comment]
The build works with node version `6.9.0`. Thanks.

**Comment by maoo** [comment]
Hi @HarsimranSingh , I'm stuck on the `Testing` phase of the README, where it asks me to run the `grunt deploy` command; as I'm running on macOS, I'm using `--target=/Users/m/OpenFin/Runtime/8.56.24.41/OpenFin.app/Contents/Resources` as parameter, though I'm not sure if that is correct.

After running the `grunt deploy` command, the `openfin --config app.json --launch` command fails with the following error:

```
[INFO:CONSOLE(339)] "Error: Invalid package /Users/m/OpenFin/Runtime/8.56.24.41/OpenFin.app/Contents/Resources/js-adapter.asar
Error: Invalid package /Users/m/OpenFin/Runtime/8.56.24.41/OpenFin.app/Contents/Resources/js-adapter.asar
    at invalidArchiveError (ELECTRON_ASAR.js:211:19)
    at Object.fsToDecorate.readFileSync (ELECTRON_ASAR.js:637:9)
    at Object.<anonymous> (/Users/m/OpenFin/Runtime/8.56.24.41/OpenFin.app/Contents/Resources/default_app/src/renderer/main.js:59:21)
    at Object.<anonymous> (/Users/m/OpenFin/Runtime/8.56.24.41/OpenFin.app/Contents/Resources/default_app/src/renderer/main.js:71:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)", source: /Users/m/OpenFin/Runtime/8.56.24.41/OpenFin.app/Contents/Resources/openfin.asar/renderer/init.js (339)
```

If I check the folder's content, I can't find a `js-adapter.asar`, though there is a `adapter.asar` and `openfin.asar`.

Please let me know if you want me to create a separate issue with this content.

TY.

**Comment by HarsimranSingh** [comment]
Hi @maoo,

Sorry about getting back to you so late. Changes have been made since version `8.56.24.41` that make the develop branch of the core incompatible with older versions. I'd recommend checking out the `runtime-v8.56.24.41` tag and developing off that. If you want to use the develop branch of the core, target `canary` as your runtime version. Hope this helps!

-Sim

**Comment by maoo** [comment]
Hi @HarsimranSingh , I tried checking out `runtime-v8.56.24.41` and follow all README instructions from scratch, but landed on the same result. Haven't tried the `canary` runtime yet, I'd prefer building a stable version before moving to `develop` branch. TY!

**Comment by HarsimranSingh** [comment]
I'd recommend killing all running `8.56.24.41` processes, deleting `%LOCALAPPDATA%\OpenFin\runtime\8.56.24.41`, and launching the runtime again via `openfin-cli` to pull down a fresh copy of the runtime again. The try `grunt deploy --target=...`. Hopefully this resolves the issue.

-Sim
